export interface LeaveRequestType {
  requestId: number;
  employeeId: number; 
  employeeAvatarUrl: string;
  employeePosition: string;
  employeeFirstname: string;
  employeeLastname: string;
  leaveType: string;
  startDate: string; // Using ISO string format (YYYY-MM-DD)
  endDate: string; // Using ISO string format (YYYY-MM-DD)
  reason: string;
  latestStatus: 'Pending' | 'Approved' | 'Rejected';
  rejectionReason?: string | null;
  isHalfDay: boolean; // True if the *entire* request is a single half-day
  isMorning: boolean | null; // Relevant only if isHalfDay is true
  isFirstHalfDay: boolean; // True if the first day of a multi-day leave is a half day
  isLastHalfDay: boolean; // True if the last day of a multi-day leave is a half day
}

export const mockLeaveRequests: LeaveRequestType[] = [
  {
    requestId: 1,
    employeeId: 12,
    employeeFirstname: "Leo", 
    employeeLastname: "Jackson",
    employeeAvatarUrl: "/avatars/leo.jpg",
    employeePosition: "QA Engineer",
    leaveType: 'Annual',
    startDate: '2025-11-03',
    endDate: '2025-11-07',
    reason: 'Family vacation',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 2,
    employeeId: 15,
    employeeFirstname: "Oscar", 
    employeeLastname: "Martin",
    employeeAvatarUrl: "/avatars/oscar.jpg",
    employeePosition: "Mobile Developer",
    leaveType: 'Sick',
    startDate: '2025-11-05',
    endDate: '2025-11-05',
    reason: 'Flu',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false, 
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 3,
    employeeId: 11,
    employeeFirstname: "Karen", 
    employeeLastname: "Thomas",
    employeeAvatarUrl: "/avatars/karen.jpg",
    employeePosition: "Finance Manager",
    leaveType: 'Personal',
    startDate: '2025-11-10',
    endDate: '2025-11-10',
    reason: 'Dentist appointment',
    latestStatus: 'Pending',
    rejectionReason: null,
    isHalfDay: true, 
    isMorning: true, 
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 4,
    employeeId: 3,
    employeeFirstname: "Charlie", 
    employeeLastname: "Williams",
    employeeAvatarUrl: "/avatars/charlie.jpg",
    employeePosition: "Content Strategist",
    leaveType: 'Personal',
    startDate: '2025-11-12',
    endDate: '2025-11-12',
    reason: 'Parent-teacher meeting',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: true, 
    isMorning: false, 
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 5,
    employeeId: 12,
    employeeFirstname: "Leo", 
    employeeLastname: "Jackson",
    employeeAvatarUrl: "/avatars/leo.jpg",
    employeePosition: "QA Engineer",
    leaveType: 'Sick',
    startDate: '2025-11-17',
    endDate: '2025-11-19',
    reason: 'Food poisoning',
    latestStatus: 'Pending',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 6,
    employeeId: 14,
    employeeFirstname: "Nina", 
    employeeLastname: "Harris",
    employeeAvatarUrl: "/avatars/nina.jpg",
    employeePosition: "Marketing Lead",
    leaveType: 'Personal',
    startDate: '2025-11-20',
    endDate: '2025-11-20',
    reason: 'Concert',
    latestStatus: 'Rejected',
    rejectionReason: 'Non-essential travel during peak period.',
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 7,
    employeeId: 11,
    employeeFirstname: "Karen", 
    employeeLastname: "Thomas",
    employeeAvatarUrl: "/avatars/karen.jpg",
    employeePosition: "Finance Manager",
    leaveType: 'Annual',
    startDate: '2025-12-01',
    endDate: '2025-12-05',
    reason: 'Trip to Japan',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 8,
    employeeId: 15,
    employeeFirstname: "Oscar", 
    employeeLastname: "Martin",
    employeeAvatarUrl: "/avatars/oscar.jpg",
    employeePosition: "Mobile Developer",
    leaveType: 'Bereavement',
    startDate: '2025-12-08',
    endDate: '2025-12-10',
    reason: 'Funeral service',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 9,
    employeeId: 13,
    employeeFirstname: "Mona", 
    employeeLastname: "White",
    employeeAvatarUrl: "/avatars/mona.jpg",
    employeePosition: "Training Coordinator",
    leaveType: 'Annual',
    startDate: '2025-12-15',
    endDate: '2025-12-19',
    reason: 'Holiday leave',
    latestStatus: 'Pending',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 10,
    employeeId: 12,
    employeeFirstname: "Leo", 
    employeeLastname: "Jackson",
    employeeAvatarUrl: "/avatars/leo.jpg",
    employeePosition: "QA Engineer",
    leaveType: 'Annual',
    startDate: '2025-12-22',
    endDate: '2025-12-26',
    reason: 'Christmas holiday',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 11,
    employeeId: 10,
    employeeFirstname: "Jack", 
    employeeLastname: "Anderson",
    employeeAvatarUrl: "/avatars/jack.jpg",
    employeePosition: "Sales Associate Lead",
    leaveType: 'Personal',
    startDate: '2026-01-05',
    endDate: '2026-01-07',
    reason: 'Moving house',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: true, 
    isLastHalfDay: false,
  },
  {
    requestId: 12,
    employeeId: 4,
    employeeFirstname: "David", 
    employeeLastname: "Brown",
    employeeAvatarUrl: "/avatars/david.jpg",
    employeePosition: "Sales Executive",
    leaveType: 'Unpaid',
    startDate: '2026-01-12',
    endDate: '2026-01-14',
    reason: 'Personal project',
    latestStatus: 'Rejected',
    rejectionReason: 'Insufficient notice provided.',
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 13,
    employeeId: 3,
    employeeFirstname: "Charlie", 
    employeeLastname: "Williams",
    employeeAvatarUrl: "/avatars/charlie.jpg",
    employeePosition: "Content Strategist",
    leaveType: 'Annual',
    startDate: '2026-01-19',
    endDate: '2026-01-21',
    reason: 'Attending wedding',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: true, 
  },
  {
    requestId: 14,
    employeeId: 15,
    employeeFirstname: "Oscar", 
    employeeLastname: "Martin",
    employeeAvatarUrl: "/avatars/oscar.jpg",
    employeePosition: "Mobile Developer",
    leaveType: 'Paternity',
    startDate: '2026-01-26',
    endDate: '2026-01-30',
    reason: 'Birth of child',
    latestStatus: 'Approved',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: false,
    isLastHalfDay: false,
  },
  {
    requestId: 15,
    employeeId: 2,
    employeeFirstname: "Bob", 
    employeeLastname: "Johnson",
    employeeAvatarUrl: "/avatars/bob.jpg",
    employeePosition: "Senior Backend Engineer",
    leaveType: 'Sick',
    startDate: '2026-02-02',
    endDate: '2026-02-04',
    reason: 'Migraine',
    latestStatus: 'Pending',
    rejectionReason: null,
    isHalfDay: false,
    isMorning: null,
    isFirstHalfDay: true, 
    isLastHalfDay: true, 
  },
];

