export interface LeaveRequestType {
  // Joined Employee Data (as requested)
  employee_id: number;
  employee_profile: string;
  employee_position: string;
  employee_first_name: string;
  employee_last_name: string;
  employee_division_name: string;
  employee_department_name: string;

  // Core Leave Request Data (matches Go struct)
  request_id: number;
  leave_type: string;
  start_date: string;       // Changed from 'time' to 'string' (YYYY-MM-DD)
  end_date: string;         // Changed from 'time' to 'string' (YYYY-MM-DD)
  reason: string | null;    // Changed to allow null (for Go *string)
  latest_status: 'Pending' | 'Approved' | 'Rejected' | 'Canceled' | 'Modified' | 'Revoked'; // FIXED: Added 'Revoked'
  reject_reason: string | null; // Changed to allow null (for Go *string)
  is_half_day: boolean | null;    // Changed to allow null (for Go *bool)
  is_morning: boolean | null;     // (for Go *bool)
  is_first_half_day: boolean | null; // Changed to allow null (for Go *bool)
  is_last_half_day: boolean | null;  // Changed to allow null (for Go *bool)
  latest_timestamp: string; // Changed from 'time' to 'string' (ISO 8601)
}



/**
 * Mock data for leave requests.
 * - Property names are updated to snake_case to match the Go backend.
 * - `latest_timestamp` is added, populated from mockStatusHistory.
 * - ADDED: 23 new requests (IDs 18-40) for more comprehensive mock data.
 */
export const mockLeaveRequests: LeaveRequestType[] = [
  {
    request_id: 1,
    employee_id: 12,
    employee_first_name: "Leo",
    employee_last_name: "Jackson",
    employee_profile: "/avatars/leo.jpg",
    employee_position: "QA Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "QA",
    leave_type: 'Annual',
    start_date: '2025-11-03',
    end_date: '2025-11-07',
    reason: 'Family vacation',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-08-21T11:30:00Z',
  },
  {
    request_id: 2,
    employee_id: 15,
    employee_first_name: "Oscar",
    employee_last_name: "Martin",
    employee_profile: "/avatars/oscar.jpg",
    employee_position: "Mobile Developer",
    employee_division_name: "Engineering",
    employee_department_name: "Mobile",
    leave_type: 'Sick',
    start_date: '2025-09-05',
    end_date: '2025-09-05',
    reason: 'Flu',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-09-04T08:30:00Z',
  },
  {
    request_id: 3,
    employee_id: 11,
    employee_first_name: "Karen",
    employee_last_name: "Thomas",
    employee_profile: "/avatars/karen.jpg",
    employee_position: "Finance Manager",
    employee_division_name: "Finance",
    employee_department_name: "Audit",
    leave_type: 'Personal',
    start_date: '2025-09-10',
    end_date: '2025-09-10',
    reason: 'Dentist appointment',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: true,
    is_morning: true,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-09-05T14:20:00Z',
  },
  {
    request_id: 4,
    employee_id: 3,
    employee_first_name: "Charlie",
    employee_last_name: "Williams",
    employee_profile: "/avatars/charlie.jpg",
    employee_position: "Content Strategist",
    employee_division_name: "Marketing",
    employee_department_name: "Digital",
    leave_type: 'Personal',
    start_date: '2025-09-12',
    end_date: '2025-09-12',
    reason: 'Parent-teacher meeting',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: true,
    is_morning: false,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-09-06T16:05:00Z',
  },
  {
    request_id: 5,
    employee_id: 12,
    employee_first_name: "Leo",
    employee_last_name: "Jackson",
    employee_profile: "/avatars/leo.jpg",
    employee_position: "QA Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "QA",
    leave_type: 'Sick',
    start_date: '2025-09-17',
    end_date: '2025-09-19',
    reason: 'Food poisoning',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-09-16T18:00:00Z',
  },
  {
    request_id: 6,
    employee_id: 14,
    employee_first_name: "Nina",
    employee_last_name: "Harris",
    employee_profile: "/avatars/nina.jpg",
    employee_position: "Marketing Lead",
    employee_division_name: "Marketing",
    employee_department_name: "PR",
    leave_type: 'Personal',
    start_date: '2025-09-20',
    end_date: '2025-09-20',
    reason: 'Concert',
    latest_status: 'Rejected',
    reject_reason: 'Non-essential travel during peak period.',
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-09-11T15:30:00Z',
  },
  {
    request_id: 7,
    employee_id: 11,
    employee_first_name: "Karen",
    employee_last_name: "Thomas",
    employee_profile: "/avatars/karen.jpg",
    employee_position: "Finance Manager",
    employee_division_name: "Finance",
    employee_department_name: "Audit",
    leave_type: 'Annual',
    start_date: '2025-10-01',
    end_date: '2025-10-05',
    reason: 'Trip to Japan',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-09-13T10:15:00Z',
  },
  {
    request_id: 8,
    employee_id: 15,
    employee_first_name: "Oscar",
    employee_last_name: "Martin",
    employee_profile: "/avatars/oscar.jpg",
    employee_position: "Mobile Developer",
    employee_division_name: "Engineering",
    employee_department_name: "Mobile",
    leave_type: 'Bereavement',
    start_date: '2025-10-08',
    end_date: '2025-10-10',
    reason: 'Funeral service',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-10-05T13:10:00Z',
  },
  {
    request_id: 9,
    employee_id: 13,
    employee_first_name: "Mona",
    employee_last_name: "White",
    employee_profile: "/avatars/mona.jpg",
    employee_position: "Training Coordinator",
    employee_division_name: "HR",
    employee_department_name: "Training",
    leave_type: 'Annual',
    start_date: '2025-10-15',
    end_date: '2025-10-19',
    reason: 'Holiday leave',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-10-08T16:45:00Z',
  },
  {
    request_id: 10,
    employee_id: 12,
    employee_first_name: "Leo",
    employee_last_name: "Jackson",
    employee_profile: "/avatars/leo.jpg",
    employee_position: "QA Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "QA",
    leave_type: 'Annual',
    start_date: '2025-10-22',
    end_date: '2025-10-26',
    reason: 'Christmas holiday',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-10-11T14:20:00Z',
  },
  {
    request_id: 11,
    employee_id: 10,
    employee_first_name: "Jack",
    employee_last_name: "Anderson",
    employee_profile: "/avatars/jack.jpg",
    employee_position: "Sales Associate Lead",
    employee_division_name: "Sales",
    employee_department_name: "Retail",
    leave_type: 'Personal',
    start_date: '2025-08-05',
    end_date: '2025-08-07',
    reason: 'Moving house',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: true,
    is_last_half_day: false,
    latest_timestamp: '2025-08-02T15:00:00Z',
  },
  {
    request_id: 12,
    employee_id: 4,
    employee_first_name: "David",
    employee_last_name: "Brown",
    employee_profile: "/avatars/david.jpg",
    employee_position: "Sales Executive",
    employee_division_name: "Sales",
    employee_department_name: "B2B",
    leave_type: 'Unpaid',
    start_date: '2025-08-12',
    end_date: '2025-08-14',
    reason: 'Personal project',
    latest_status: 'Rejected',
    reject_reason: 'Insufficient notice provided.',
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-08-05T17:00:00Z',
  },
  {
    request_id: 13,
    employee_id: 3,
    employee_first_name: "Charlie",
    employee_last_name: "Williams",
    employee_profile: "/avatars/charlie.jpg",
    employee_position: "Content Strategist",
    employee_division_name: "Marketing",
    employee_department_name: "Digital",
    leave_type: 'Annual',
    start_date: '2025-08-19',
    end_date: '2025-08-21',
    reason: 'Attending wedding',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: true,
    latest_timestamp: '2025-08-11T09:00:00Z',
  },
  {
    request_id: 14,
    employee_id: 15,
    employee_first_name: "Oscar",
    employee_last_name: "Martin",
    employee_profile: "/avatars/oscar.jpg",
    employee_position: "Mobile Developer",
    employee_division_name: "Engineering",
    employee_department_name: "Mobile",
    leave_type: 'Paternity',
    start_date: '2025-08-26',
    end_date: '2025-08-30',
    reason: 'Birth of child',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-08-15T11:05:00Z',
  },
  {
    request_id: 15,
    employee_id: 2,
    employee_first_name: "Bob",
    employee_last_name: "Johnson",
    employee_profile: "/avatars/bob.jpg",
    employee_position: "Senior Backend Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "Backend",
    leave_type: 'Sick',
    start_date: '2025-07-02',
    end_date: '2025-07-04',
    reason: 'Migraine',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: true,
    is_last_half_day: true,
    latest_timestamp: '2025-07-01T22:00:00Z',
  },
  // --- NEW MOCK DATA ---
  {
    request_id: 16,
    employee_id: 5,
    employee_first_name: "Eva",
    employee_last_name: "Davis",
    employee_profile: "/avatars/eva.jpg",
    employee_position: "Software Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "Frontend",
    leave_type: 'Personal',
    start_date: '2025-11-10',
    end_date: '2025-11-10',
    reason: 'Moving apartment',
    latest_status: 'Canceled',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-02T10:00:00Z',
  },
  {
    request_id: 17,
    employee_id: 8,
    employee_first_name: "Hannah",
    employee_last_name: "Moore",
    employee_profile: "/avatars/hannah.jpg",
    employee_position: "Marketing Specialist",
    employee_division_name: "Marketing",
    employee_department_name: "Events",
    leave_type: 'Annual',
    start_date: '2025-11-20',
    end_date: '2025-11-22',
    reason: 'Short trip (modified date)',
    latest_status: 'Pending', // A 'Modified' request is still 'Pending'
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-05T11:00:00Z',
  },
  // --- ADDED 23 NEW REQUESTS (18-40) ---
  {
    request_id: 18,
    employee_id: 7,
    employee_first_name: "Grace",
    employee_last_name: "Wilson",
    employee_profile: "/avatars/grace.jpg",
    employee_position: "Accountant",
    employee_division_name: "Finance",
    employee_department_name: "Accounts",
    leave_type: 'Annual',
    start_date: '2025-11-15',
    end_date: '2025-11-15',
    reason: 'Day trip',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-06T09:00:00Z',
  },
  {
    request_id: 19,
    employee_id: 4,
    employee_first_name: "David",
    employee_last_name: "Brown",
    employee_profile: "/avatars/david.jpg",
    employee_position: "Sales Executive",
    employee_division_name: "Sales",
    employee_department_name: "B2B",
    leave_type: 'Sick',
    start_date: '2025-11-06',
    end_date: '2025-11-07',
    reason: 'Cold',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-06T10:05:00Z',
  },
  {
    request_id: 20,
    employee_id: 9,
    employee_first_name: "Ian",
    employee_last_name: "Taylor",
    employee_profile: "/avatars/ian.jpg",
    employee_position: "DevOps Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "DevOps",
    leave_type: 'Personal',
    start_date: '2025-11-12',
    end_date: '2025-11-12',
    reason: 'Bank appointment',
    latest_status: 'Rejected',
    reject_reason: 'Critical deployment day. Please reschedule.',
    is_half_day: true,
    is_morning: false,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-07T14:00:00Z',
  },
  {
    request_id: 21,
    employee_id: 13,
    employee_first_name: "Mona",
    employee_last_name: "White",
    employee_profile: "/avatars/mona.jpg",
    employee_position: "Training Coordinator",
    employee_division_name: "HR",
    employee_department_name: "Training",
    leave_type: 'Annual',
    start_date: '2025-11-20',
    end_date: '2025-11-21',
    reason: 'Long weekend',
    latest_status: 'Canceled',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-08T11:00:00Z',
  },
  {
    request_id: 22,
    employee_id: 3,
    employee_first_name: "Charlie",
    employee_last_name: "Williams",
    employee_profile: "/avatars/charlie.jpg",
    employee_position: "Content Strategist",
    employee_division_name: "Marketing",
    employee_department_name: "Digital",
    leave_type: 'Personal',
    start_date: '2025-11-18',
    end_date: '2025-11-18',
    reason: 'Plumber visit',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: true,
    is_morning: true,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-08T15:30:00Z',
  },
  {
    request_id: 23,
    employee_id: 5,
    employee_first_name: "Eva",
    employee_last_name: "Davis",
    employee_profile: "/avatars/eva.jpg",
    employee_position: "Software Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "Frontend",
    leave_type: 'Sick',
    start_date: '2025-11-10',
    end_date: '2025-11-11',
    reason: 'Migraine',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-09T08:00:00Z',
  },
  {
    request_id: 24,
    employee_id: 6,
    employee_first_name: "Frank",
    employee_last_name: "Miller",
    employee_profile: "/avatars/frank.jpg",
    employee_position: "HR Specialist",
    employee_division_name: "HR",
    employee_department_name: "Payroll",
    leave_type: 'Annual',
    start_date: '2025-12-01',
    end_date: '2025-12-05',
    reason: 'Holiday',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-09T17:00:00Z',
  },
  {
    request_id: 25,
    employee_id: 1,
    employee_first_name: "Alice",
    employee_last_name: "Smith",
    employee_profile: "/avatars/alice.jpg",
    employee_position: "HR Manager",
    employee_division_name: "HR",
    employee_department_name: "Recruitment",
    leave_type: 'Personal',
    start_date: '2025-11-14',
    end_date: '2025-11-14',
    reason: 'School event',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-10T09:15:00Z',
  },
  {
    request_id: 26,
    employee_id: 2,
    employee_first_name: "Bob",
    employee_last_name: "Johnson",
    employee_profile: "/avatars/bob.jpg",
    employee_position: "Senior Backend Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "Backend",
    leave_type: 'Annual',
    start_date: '2025-11-24',
    end_date: '2025-11-26',
    reason: 'Thanksgiving travel',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-10T11:00:00Z',
  },
  {
    request_id: 27,
    employee_id: 8,
    employee_first_name: "Hannah",
    employee_last_name: "Moore",
    employee_profile: "/avatars/hannah.jpg",
    employee_position: "Marketing Specialist",
    employee_division_name: "Marketing",
    employee_department_name: "Events",
    leave_type: 'Sick',
    start_date: '2025-11-13',
    end_date: '2025-11-14',
    reason: 'Stomach bug',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-11T13:45:00Z',
  },
  {
    request_id: 28,
    employee_id: 12,
    employee_first_name: "Leo",
    employee_last_name: "Jackson",
    employee_profile: "/avatars/leo.jpg",
    employee_position: "QA Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "QA",
    leave_type: 'Annual',
    start_date: '2025-12-22',
    end_date: '2025-12-26',
    reason: 'Christmas',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-12T10:30:00Z',
  },
  {
    request_id: 29,
    employee_id: 15,
    employee_first_name: "Oscar",
    employee_last_name: "Martin",
    employee_profile: "/avatars/oscar.jpg",
    employee_position: "Mobile Developer",
    employee_division_name: "Engineering",
    employee_department_name: "Mobile",
    leave_type: 'Personal',
    start_date: '2025-11-19',
    end_date: '2025-11-19',
    reason: 'Drivers license renewal',
    latest_status: 'Canceled',
    reject_reason: null,
    is_half_day: true,
    is_morning: false,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-12T16:00:00Z',
  },
  {
    request_id: 30,
    employee_id: 7,
    employee_first_name: "Grace",
    employee_last_name: "Wilson",
    employee_profile: "/avatars/grace.jpg",
    employee_position: "Accountant",
    employee_division_name: "Finance",
    employee_department_name: "Accounts",
    leave_type: 'Sick',
    start_date: '2025-11-17',
    end_date: '2025-11-17',
    reason: 'Headache',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-13T09:00:00Z',
  },
  {
    request_id: 31,
    employee_id: 4,
    employee_first_name: "David",
    employee_last_name: "Brown",
    employee_profile: "/avatars/david.jpg",
    employee_position: "Sales Executive",
    employee_division_name: "Sales",
    employee_department_name: "B2B",
    leave_type: 'Personal',
    start_date: '2025-11-21',
    end_date: '2025-11-21',
    reason: 'Family matter',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-13T10:20:00Z',
  },
  {
    request_id: 32,
    employee_id: 9,
    employee_first_name: "Ian",
    employee_last_name: "Taylor",
    employee_profile: "/avatars/ian.jpg",
    employee_position: "DevOps Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "DevOps",
    leave_type: 'Annual',
    start_date: '2025-11-27',
    end_date: '2025-11-28',
    reason: 'Thanksgiving',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-13T14:30:00Z',
  },
  {
    request_id: 33,
    employee_id: 13,
    employee_first_name: "Mona",
    employee_last_name: "White",
    employee_profile: "/avatars/mona.jpg",
    employee_position: "Training Coordinator",
    employee_division_name: "HR",
    employee_department_name: "Training",
    leave_type: 'Sick',
    start_date: '2025-11-14',
    end_date: '2025-11-14',
    reason: 'Doctors appointment',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: true,
    is_morning: true,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-14T08:30:00Z',
  },
  {
    request_id: 34,
    employee_id: 3,
    employee_first_name: "Charlie",
    employee_last_name: "Williams",
    employee_profile: "/avatars/charlie.jpg",
    employee_position: "Content Strategist",
    employee_division_name: "Marketing",
    employee_department_name: "Digital",
    leave_type: 'Annual',
    start_date: '2025-12-01',
    end_date: '2025-12-03',
    reason: 'Vacation',
    latest_status: 'Rejected',
    reject_reason: 'Conflict with project deadline.',
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-14T11:00:00Z',
  },
  {
    request_id: 35,
    employee_id: 5,
    employee_first_name: "Eva",
    employee_last_name: "Davis",
    employee_profile: "/avatars/eva.jpg",
    employee_position: "Software Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "Frontend",
    leave_type: 'Personal',
    start_date: '2025-11-17',
    end_date: '2025-11-17',
    reason: 'Repairman coming',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: true,
    is_morning: false,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-15T10:00:00Z',
  },
  {
    request_id: 36,
    employee_id: 10,
    employee_first_name: "Jack",
    employee_last_name: "Anderson",
    employee_profile: "/avatars/jack.jpg",
    employee_position: "Sales Associate Lead",
    employee_division_name: "Sales",
    employee_department_name: "Retail",
    leave_type: 'Annual',
    start_date: '2025-11-24',
    end_date: '2025-11-26',
    reason: 'Vacation',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-15T13:00:00Z',
  },
  {
    request_id: 37,
    employee_id: 11,
    employee_first_name: "Karen",
    employee_last_name: "Thomas",
    employee_profile: "/avatars/karen.jpg",
    employee_position: "Finance Manager",
    employee_division_name: "Finance",
    employee_department_name: "Audit",
    leave_type: 'Personal',
    start_date: '2025-11-20',
    end_date: '2025-11-20',
    reason: 'Personal day',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-16T11:00:00Z',
  },
  {
    request_id: 38,
    employee_id: 14,
    employee_first_name: "Nina",
    employee_last_name: "Harris",
    employee_profile: "/avatars/nina.jpg",
    employee_position: "Marketing Lead",
    employee_division_name: "Marketing",
    employee_department_name: "PR",
    leave_type: 'Sick',
    start_date: '2025-11-18',
    end_date: '2025-11-18',
    reason: 'Not feeling well',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-17T08:00:00Z',
  },
  {
    request_id: 39,
    employee_id: 1,
    employee_first_name: "Alice",
    employee_last_name: "Smith",
    employee_profile: "/avatars/alice.jpg",
    employee_position: "HR Manager",
    employee_division_name: "HR",
    employee_department_name: "Recruitment",
    leave_type: 'Annual',
    start_date: '2025-12-08',
    end_date: '2025-12-10',
    reason: 'Short vacation',
    latest_status: 'Approved',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-17T10:00:00Z',
  },
  {
    request_id: 40,
    employee_id: 2,
    employee_first_name: "Bob",
    employee_last_name: "Johnson",
    employee_profile: "/avatars/bob.jpg",
    employee_position: "Senior Backend Engineer",
    employee_division_name: "Engineering",
    employee_department_name: "Backend",
    leave_type: 'Sick',
    start_date: '2025-11-19',
    end_date: '2025-11-19',
    reason: 'Food poisoning',
    latest_status: 'Pending',
    reject_reason: null,
    is_half_day: false,
    is_morning: null,
    is_first_half_day: false,
    is_last_half_day: false,
    latest_timestamp: '2025-11-18T22:00:00Z',
  },
];

